<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <BaseOutputPath>..\..\UnityTemplate\Assets\Plugins\Native</BaseOutputPath>
    <UnityVersion Condition="'$(UnityVersion)' == ''">2022.3.62f3</UnityVersion>
    <Configurations>Debug;Release;Unity2022;Unity2023</Configurations>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Library\**\*.cs"></Compile>
    <Compile Remove="Packages\**\*.cs"></Compile>
    <Compile Remove="Logs\**\*.cs"></Compile>
    <Compile Remove="ProjectSettings\**\*.cs"></Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Projects\ParrotNativeCode\ParrotNativeCode.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Unity.Localization">
      <HintPath>UnityDLL\6000.4.0f1\Unity.Localization.dll</HintPath>
    </Reference>
    <Reference Include="UnityEditor.CoreModule">
      <HintPath>UnityDLL\2023.1.20f1\UnityEditor.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEditor.UI">
      <HintPath>UnityDLL\2022.3.62f3\UnityEditor.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>UnityDLL\2023.1.20f1\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>UnityDLL\2023.1.20f1\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>UnityDLL\2022.3.62f3\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
      <EmbedInteropTypes></EmbedInteropTypes>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>UnityDLL\2023.1.20f1\UnityEngine.UIModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
