<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <BaseOutputPath>..\..\UnityTemplate\Assets\Packages\com.sludgyparrot.ai\Runtime\Plugins</BaseOutputPath>
    <Configurations>Debug;Release;Unity2022;Unity2023</Configurations>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\UnityDLL\2023.1.20f1\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Code\Runtime\" />
  </ItemGroup>

</Project>
