/*

Parrot Code
Copyright (c) 2026 Sludgy Parrot (Pty) Ltd. All Rights Reserved.

This source code is proprietary and confidential software owned by
Sludgy Parrot (Pty) Ltd.

Parrot Code is a commercial software product developed and distributed
by Sludgy Parrot (Pty) Ltd.

Unauthorized copying, modification, distribution, sublicensing,
reverse engineering, decompilation, disclosure, or use of this
software, in whole or in part, is strictly prohibited without
prior written permission from Sludgy Parrot (Pty) Ltd.

This software is provided under the terms of a separate license
agreement. Possession of this source code does not grant any rights
to use, modify, distribute, or create derivative works unless
explicitly authorized by a valid written license.

THE SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, EXCEPT AS REQUIRED BY APPLICABLE LAW.

For licensing inquiries:
licensing@sludgyparrot.com

*/

namespace ParrotCode.Native.Shared
{
    /// <summary>
    /// Represents a direction relative to the device screen.
    /// </summary>
    public enum ScreenDirection
    {
        /// <summary>
        /// Towards the top of the screen.
        /// </summary>
        Up,

        /// <summary>
        /// Towards the bottom of the screen.
        /// </summary>
        Down,

        /// <summary>
        /// Towards the left side of the screen.
        /// </summary>
        Left,

        /// <summary>
        /// Towards the right side of the screen.
        /// </summary>
        Right
    }

    /// <summary>
    /// Represents a direction relative to a transform's local coordinate system.
    /// </summary>
    public enum TransformDirection
    {
        /// <summary>
        /// In the transform's forward direction.
        /// </summary>
        Forward,

        /// <summary>
        /// In the transform's backward direction.
        /// </summary>
        Backward,

        /// <summary>
        /// In the transform's left direction.
        /// </summary>
        Left,

        /// <summary>
        /// In the transform's right direction.
        /// </summary>
        Right
    }

    /// <summary>
    /// Represents the type of output generated by a Unity build target.
    /// </summary>
    public enum BuildOutput
    {
        /// <summary>
        /// The build output is a single file (for example, an APK or EXE).
        /// </summary>
        File,

        /// <summary>
        /// The build output is a directory containing multiple files (for example, a WebGL build or an iOS Xcode project).
        /// </summary>
        Folder
    }
}
