<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <BaseOutputPath>..\..\UnityTemplate\Assets\Plugins\Multiplayer</BaseOutputPath>
    <UnityVersion Condition="'$(UnityVersion)' == ''">2022.3.62f3</UnityVersion>
    <Configurations>Debug;Release;Unity2022;Unity2023</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configurations)' == 'Unity2022'">
    <UnityVersion>2022.3.62f3</UnityVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'Configuration' == 'Unity2023'">
    <UnityVersion>2023.1.20f1</UnityVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Unity.Netcode.Components">
      <HintPath>..\..\UnityDLL\$(UnityVersion)\NetCode\Unity.Netcode.Components.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Netcode.Editor">
      <HintPath>..\..\UnityDLL\$(UnityVersion)\NetCode\Unity.Netcode.Editor.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Netcode.Editor.CodeGen">
      <HintPath>..\..\UnityDLL\$(UnityVersion)\NetCode\Unity.Netcode.Editor.CodeGen.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Netcode.Editor.PackageChecker">
      <HintPath>..\..\UnityDLL\$(UnityVersion)\NetCode\Unity.Netcode.Editor.PackageChecker.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Netcode.Runtime">
      <HintPath>..\..\UnityDLL\$(UnityVersion)\NetCode\Unity.Netcode.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Networking.Editor">
      <HintPath>..\..\UnityDLL\$(UnityVersion)\NetCode\Unity.Networking.Editor.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Networking.Transport">
      <HintPath>..\..\UnityDLL\$(UnityVersion)\NetCode\Unity.Networking.Transport.dll</HintPath>
    </Reference>
    <Reference Include="UnityEditor">
      <HintPath>..\..\UnityDLL\$(UnityVersion)\UnityEditor.dll</HintPath>
      <private>false</private>
    </Reference>
    <Reference Include="UnityEditor.Graphs">
      <HintPath>..\..\UnityDLL\$(UnityVersion)\UnityEditor.Graphs.dll</HintPath>
      <private>false</private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\UnityDLL\$(UnityVersion)\UnityEngine.dll</HintPath>
      <private>false</private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Code\Editor\" />
    <Folder Include="Code\Runtime\" />
  </ItemGroup>

</Project>
